### ISSUE TITLE
func verifyStringSliceFileDefault comment is now out of date

### ISSUE THREAD

**Issue by pporada-gl** [opencredo/terrahelp#14]
The comment contains links to codegangsta/cli which have both been resolved. It seems like that function isn't needed anymore.
https://github.com/opencredo/terrahelp/blob/master/commands.go#L433-L455

**Comment by nickithewatt** [comment]
Hi @pporada-gl I believe the function is still required although its purpose has somewhat changed a bit. Although the specific issues cited as part of the initial reason for the workaround function have been fixed (i.e. weird behaviour with defaults) these fixes are currently only available on the as yet unreleased v2 branch, and as far as I can tell, there is still no support for setting a destination yet. 

That said however, the function has changed and no longer looks to leverage this functionality directly anymore (this changed in https://github.com/opencredo/terrahelp/commit/f6cdcf2ee9bf0a74ce6c04ca8daea7c63d72f38d) so its probably at least worth updating the code to make this more clearer which I will do, thanks!
