### ISSUE TITLE
VAULT_NAMESPACE is not respected

### ISSUE THREAD

**Issue by yasiumaster** [opencredo/terrahelp#16]
Environment value VAULT_NAMESPACE is not taking into consideration while **terrahelp encrypt**

Is there another way to specify namespace for encryption/decryption ?

**Comment by nickithewatt** [comment]
Hi @yasiumaster Vault Namespaces (via VAULT_NAMESPACE env) is an enterprise feature which was not supported when the last version of terrahelp was built. I shall look to upgrade the latest version of the code which should hopefully pick this up

**Comment by trentrosenbaum** [comment]
Hi @yasiumaster I just wanted to mentioned that a new release [v0.7.1](https://github.com/opencredo/terrahelp/releases/tag/v0.7.1) has been made.  

The main focus has been to update the dependencies to be managed through Go Modules.  At the same time It update Vault API to v1.04 and this includes a reference to "VAULT_NAMESPACE" environment variable.

**Comment by trentrosenbaum** [comment]
The Vault client was updated within Terrahelp and this allows the use of the VAULT_NAMESPACE" environment variable.  This is now merged into master and was released.

I am going to close this issue now.
