### ISSUE TITLE
Update Terrahelp execute over Terraform 0.12.x HCL2 syntax

### ISSUE THREAD

**Issue by trentrosenbaum** [opencredo/terrahelp#22]
The current version of Terrahelp operates over Terraform 0.11.x formatted output.  The examples represent HCL before the update to HCL2 with the 0.12.x release of Terraform.  

This is represents the need for Terrahelp to be updated to process HCL2.  Along with this update the All examples should be updated with HCL2 syntax and the README files should reflect these alterations.

**Comment by rob-orr** [comment]
👍 I would love to see this working with TF `0.12`.

**Comment by trentrosenbaum** [comment]
The master branch has been updated to process 0.12 syntax and pre 0.12 syntax.  This update was merged through PR [#23 ](https://github.com/opencredo/terrahelp/pull/23).

Existing unit tests and new 0.12 output based tests are executed against the code based.  This PR focused on the masking of sensitive data in the console output.

This will be in the next release of Terrahelp.
