### ISSUE TITLE
Include SHA256 in the releases

### ISSUE THREAD

**Issue by spookyGh0st** [opencredo/terrahelp#28]
for linux-amd64 v0.7.1 it is 
```7e1c2637837b4a2b74cf7b368ef0f323ea0f7691780e01aa8ed95e374b8d933b```

**Comment by trentrosenbaum** [comment]
Starting with 0.7.4 of Terrahelp each release alongside the linux and darwin binaries will also include a file called `terrahelp.SHA256SUMS`.  This file will include the SHA 256 digest values for each of the released binaries and will allow downloads to be confirmed.

https://github.com/opencredo/terrahelp/releases/tag/v0.7.4

`
wget https://github.com/opencredo/terrahelp/releases/download/v0.7.4/terrahelp-linux-amd64
wget https://github.com/opencredo/terrahelp/releases/download/v0.7.4/terrahelp-darwin-amd64
wget https://github.com/opencredo/terrahelp/releases/download/v0.7.4/terrahelp.SHA256SUMS
shasum -a 256 -c terrahelp.SHA256SUMS

terrahelp-darwin-amd64: OK
terrahelp-linux-amd64: OK
`
