### ISSUE TITLE
GitHub Actions Integration

### ISSUE THREAD

**Issue by gesellix** [opencredo/terrahelp#34]
Hey, thanks for your nice tool, it helped me _not to_ deploy yet another service or even a GitHub Actions Runner with highly sophisticated AWS IAM Policies.

To keep things simple and still leverage modern GitHub Actions as part of our CI, I created https://github.com/gesellix/terrahelp-github-action to have a tight integration with HashiCorp's [Terraform GitHub Actions](https://github.com/hashicorp/terraform-github-actions).

Maybe other folks will search for a ready to use solution or some inspiration.

So, this one is only to give you a little heads-up. I'm going to close this issue after a few days, but feel free to close it as you see fit.

Thanks again!

**Comment by nickithewatt** [comment]
Thanks @gesellix!
